#! /bin/bash

echo "APT" | figlet
sudo apt update && sudo apt upgrade

echo "SNAP" | figlet
sudo snap refresh

echo "BREW" | figlet
brew update && brew outdated
select ANS in 'update' 'stop'; do
    [ $ANS == 'update' ] && { brew upgrade; break; }
    [ $ANS == 'stop' ] && break
done